# Generated by Django 5.2.7 on 2025-12-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_is_deleted_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_likes',
        ),
    ]
