USER_FULL_NAME_MAX_LENGTH: int = 150

USER_EMAIL_MAX_LENGTH: int = 254  

CATEGORY_NAME_MAX_LENGTH: int = 100

IDEA_TITLE_MAX_LENGTH: int = 200

PROFILE_DEFAULT_COUNT: int = 0

JWT_AUTH_HEADER_TYPE: str = "JWT"

SAFE_HTTP_METHODS: tuple[str, ...] = ("GET", "HEAD", "OPTIONS")
